const fs = require("fs/promises");
const path = require("path");
const config = require("../config");
const { contentDisposition } = require("./contentDisposition");

const baseDir = path.resolve(config.storage.localDir);

// Keys are generated by the server (uuid-based), but resolve and check
// anyway so a bad key can never point outside the upload folder.
function resolveKey(key) {
  const fullPath = path.resolve(baseDir, key);
  if (!fullPath.startsWith(baseDir + path.sep)) {
    throw new Error("Invalid storage key");
  }
  return fullPath;
}

async function save(key, buffer) {
  const fullPath = resolveKey(key);
  await fs.mkdir(path.dirname(fullPath), { recursive: true });
  await fs.writeFile(fullPath, buffer);
}

async function remove(key) {
  try {
    await fs.unlink(resolveKey(key));
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }
}

async function sendFile(res, doc) {
  const data = await fs.readFile(resolveKey(doc.storage_key));
  res.setHeader("Content-Type", doc.mime_type);
  res.setHeader("Content-Length", data.length);
  res.setHeader("Content-Disposition", contentDisposition(doc.original_name));
  res.send(data);
}

module.exports = { save, remove, sendFile };
